name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: go test -v -coverprofile=./profile.cov ./...
      
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ./profile.cov

  semantic-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run semantic-release
        if: github.repository == 'bartventer/viperenv' && github.event_name == 'push'
        run: |
          yarn global add semantic-release@17
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}