name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.22.x','1.21.x']
    env:
      PATH_TO_PROFILE: "./profile.cov"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run Tests
      run: go test -v -coverprofile=${{ env.PATH_TO_PROFILE }} ./...
      
    - name: Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ${{ env.PATH_TO_PROFILE }}

  semantic-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Run semantic-release
        if: github.repository == 'bartventer/viperenv' && github.event_name == 'push'
        run: |
          yarn global add semantic-release@17
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}